### ISSUE TITLE
Intent to package: Incomplete tags on Github, no license file and test suite on PyPI

### ISSUE THREAD

**Issue by michel-slm** [DRMacIver/hypothesis#107]
Hi @DRMacIver --

I'm interested in making Hypothesis available as a Fedora package - if/when property testing takes up among Python projects it would be really useful for us to be able to run their test suites as part of the build process (deps must be satisfied using Fedora RPM packages).

Two quandaries though -- if I use release archives from Github, not all releases seem to be available (the latest is still 1.8.2). If I use the archive on PyPI, where Hypothesis is split up into several packages,
- LICENSE.txt is missing
- tests is not packaged

I suppose I'll start by working on packaging 1.8.2 from Github (it's understandable that people installing using pip don't need the test suite etc.), but could the missing tags be pushed? Thanks!

**Comment by DRMacIver** [comment]
Thanks for looking into packaging!

Sorry, I did indeed forget to push the 1.8.3 tag. That is fixed now.

I'll fix the LICENSE.txt for the next version of pip, but it's worth noting that all of the code comes with the MPLv2 header anyway so the version there is explicitly licensed even without it.

Not shipping the tests with Hypothesis in pip is by design though. I could change it, but I'm not sure it's the right thing to do and I'd probably recommend building from the github archive if you need them.

You may wish to hold off on packaging, or at least ignore the extra packages, until the 1.9 release (scheduled for "some time this month or very beginning of next"). The separate packaging for them has proven generally very irritating for people so I'm planning to bring most of them back into the fold (the pytest plugin will remain separate).

**Comment by michel-slm** [comment]
Yeah, planning to ignore the extra packages for now, thanks. Working on 1.8.5 right now, having the core library alone would be really useful, and while someone is available on the Fedora side to do peer review I want to get it in.
