### ISSUE TITLE
Hypothesis doesn't pick up on nose's yield statements

### ISSUE THREAD

**Issue by Niksko** [DRMacIver/hypothesis#126]
I know that it says in the docs that nose isn't properly tested with hypothesis, but I don't think it's implied strongly enough. The ability in nose to yield functions that assert things (eg. for testing a range of data with the same test) was one of the reasons I started using nose, however it doesn't appear that Hypothesis picks on up failing asserts inside of yields. So perhaps this could either be fixed, or it could be expressly mentioned in the compatibility section of the docs, because this yeild syntax seems to be a big selling point of nose.

Here's the code to reproduce it:

```python
@given(just(''))
def test_shouldfail(s):
    for _ in range(10):
        assert False
```

This fails as expected. However:

```python
def alwaysfails(s)
    assert False
@given(just(''))
def test_shouldfail(s):
    for _ in range(10):
        yield alwaysfail, s
```

Should fail but doesn't.

**Comment by DRMacIver** [comment]
I don't really feel like this is an instance of Hypothesis "not being properly tested" with nose. It's true this doesn't work, but that's mostly because you're giving Hypothesis something that isn't a normal test but is instead a weird nose-specific thing. Hypothesis's compatibility promise is that it works with things where you can run a function and see if it errors, which is not what nose is doing here. I'm not even sure what the semantics of the interaction between yield tests and Hypothesis could reasonably be TBH.

At any rate, I'll document this, but it's definitely not going to work unless someone else takes on the task.

**Comment by DRMacIver** [comment]
(Note that taking on the task probably involves writing a nose plugin. A test being a generator function has too many different meanings to unambiguously assign a single one across all uses of Hypothesis)

**Comment by Niksko** [comment]
No worries. I wasn't necessarily expecting to be fixed, I just thought it might be worth mentioning.

**Comment by DRMacIver** [comment]
Yeah, you're right that it's worth attaching a warning about. Just about to push some documentation changes to do that.

Would you mind explaining the use case for this though? It seems a bit like feature duplication: You'd mostly use nose's yield tests for parametrizing by data, which is what Hypothesis is already doing.

**Comment by Niksko** [comment]
Yeah, thats true, you could probably do it as part of hypothesis.

Briefly, I'm writing some code now to do some simulations and calculations in game theory. So I've got a particular game, and I'm going to implement a bunch of strategies for the game. And naturally I want every single strategy to behave itself for certain inputs.

So I'm using hypothesis to test the range of inputs. Now I suppose I could just use `sampled_from`. However it feels like it doesn't really match conceptually. I want to test _each_ of the strategies across a range of inputs, as opposed to a sample of combinations of the strategies and inputs.

Anyhow, I've worked around it, so it's all good. Thanks for updating the docs, and thanks for making a really really great tool!

**Comment by DRMacIver** [comment]
Have you considered swapping the order of things? You could change it so that instead of having the yield inside the given you yield a bunch of given based tests.

The other thing I often do is just not yield, and write a test that has an assert in the body of a for loop. I actually wrote [a blog post about that](http://www.drmaciver.com/2015/08/how-to-generate-a-list-plus-an-element-of-it/) this morning.

**Comment by DRMacIver** [comment]
Notably for making that work BTW you don't have to provide all the arguments to a function using given. If you only have given specify some of them then you need to provide the rest when you call it and it will merely parametrize over the remaining ones.
