### ISSUE TITLE
Add a hook to set the random seed / state for derandomize

### ISSUE THREAD

**Issue by adamchainz** [DRMacIver/hypothesis#159]
My nose plugin [nose-randomly](https://github.com/adamchainz/nose-randomly) resets random seeds to a given number (or a number picked at the start of the test run and printed out) at the start of each test. It also resets factory boy's random state thanks to hooks it provides. It would be great if **hypothesis** in `derandomize` mode allowed you to set the seed, rather than it always being pulled from the test functions' names.

**Comment by DRMacIver** [comment]
Could you outline exactly what you need and where you need to hook in? e.g. which of the following would you prefer, or would none of the following work for you?

1. Letting you set a single global seed that Hypothesis seeds all its Random creation off
2. Having Hypothesis simply generate all its examples from a draw from random so that random.seed() would do the right thing.
3. Letting you assign a function somewhere that takes a test function and outputs a seed
4. Having an assignable Random object on methods which are decorated with given (you can already detect these with is_hypothesis_test).

I've not yet formed a preference amongst these, I'm just trying to figure out the API design space that would help with what you need.

**Comment by DRMacIver** [comment]
Oh, follow-up question: Do you actually want derandomize mode here at all? Would it be sufficient for Hypothesis to respect random.seed() when *not* running in derandomize mode?

**Comment by adamchainz** [comment]
In fact you're right, this can be done as part of normal hypothesis execution as opposed to derandomize mode. Respecting `random.seed()`, or perhaps having a public `random.Random` that can be controlled (factory boy's strategy), would be enough.

**Comment by DRMacIver** [comment]
As of 1.18.0, Hypothesis will now explicitly use the global random module for seeding its RNGs, so if you do random.seed() Hypothesis will automatically do the right thing.

**Comment by adamchainz** [comment]
Excellent, thanks.
