### ISSUE TITLE
Add easier way to do lists(..., unique_by=lambda x: x)

### ISSUE THREAD

**Issue by cdown** [DRMacIver/hypothesis#193]
`unique_by` is easy to extend, which is nice, but it would also be nice to cover what is probably the most common case -- testing object uniqueness. In this case, we can currently do `lists(..., unique_by=lambda x: x)`, but that seems a little clumsy. It would be better to have a boolean flag that could control it.

Here's basically how I imagine it:

- if `unique` is False and `unique_by` is None, then nothing happens
- if `unique` is True and `unique_by` is None, then we make the items unique using item equality
- if `unique` is True or False and `unique_by` is not None, then we implicitly set `unique` to True, and make the items unique by calling `unique_by`

**Comment by cdown** [comment]
...or maybe we just rename `unique_by` to `unique` and keep `unique_by` as a deprecated name? I think `unique_by=lambda ...` and `unique=lambda ...` are equally readable, but in `unique_by=True` and `unique=True` the latter is much more clear.

**Comment by DRMacIver** [comment]
I'm not a huge fan of overloading unique to take either a boolean or a function. It seems confusing, particularly because functions are (usually!) truthy. I'd rather keep them as separate flags.

Thing I would suggest to refine your original suggestion though: I think it should be an InvalidArgument error to set unique to True and unique_by to something non-None, otherwise you either are throwing away the unique_by argument or you're returning non-unique values when unique is True

**Comment by cdown** [comment]
Yeah, I guess that could be confusing, since we'd essentially be doing `is True` instead of `== True` which might violate the user's expectations.

Your suggestion sounds good, I'll do that.

**Comment by cdown** [comment]
#194 merged.
