### ISSUE TITLE
Timeouts don't seem to be working

### ISSUE THREAD

**Issue by ckaran** [DRMacIver/hypothesis#61]
I've written (an admittedly torturous) test to test out how well pickling works with a chunk of code I have.  The relevant section is below.

```python
with Settings(timeout=-1):
    @given(max_speed=float,
           tradingpost_probability=float,
           pause_mean=float,
           max_step_size=float,
           name=str,
           robot_call_periodicity=float)
    def test_pickling(self, max_speed, tradingpost_probability, pause_mean, 
                      max_step_size, name, robot_call_periodicity):
        assume(max_speed >= 0.0)
        assume(tradingpost_probability >= 0.0)
        assume(tradingpost_probability <= 1.0)
        assume(pause_mean > 0.0)
        assume(max_step_size > 0.0)
        assume(robot_call_periodicity > 0.0)
        assume(robot_call_periodicity < 1000.0)
```

This fails with:
> hypothesis.errors.Unsatisfiable: Unable to satisfy assumptions of hypothesis test_pickling. Only 4 examples found after 0.121668 seconds

The problem is the timeouts.  Reading through the documentation of ``core.find_satisfying_template()``, it appears that by setting the ``timeout`` setting to a negative number, hypothesis should no longer timeout; that is, it will work for as long as is necessary to generate enough examples.  However, what actually happens is that the timeouts are still defaulting to whatever the defaults are.  Is this a bug in hypothesis, or is this an error on my part?

Thanks, and thanks for writing such a fantastic library!

**Comment by DRMacIver** [comment]
This is actually user error, but I only noticed that halfway through writing that this was definitely a bug in Hypothesis, so there's at the very least a bug that this is super confusing!

What's happening is that Hypothesis has given up after it's tried a certain number of examples, and is then raising an Unsatisfiable error saying that not enough of them met the criteria because the probability of the assume hitting is too low. adaptive assume will start to kick in and find you examples, but it needs a bit more to work with than it's got here.

You can try to fix this by raising max\_examples in Settings higher. The default is 200, and I tend to run with 1000 or 2000 for hard to find cases. You could also try replacing some of your uses of floats with floats_in_range, as that will not have the same problem of difficult to hit criteria.

**Comment by ckaran** [comment]
That worked!  All it really needed was floats_in_range() to work; after I specified the probabilities using it, hypothesis Just Worked (TM)

Thanks!
Cem Karan

**Comment by DRMacIver** [comment]
The error here should now be less confusing as of the 1.3 release
