### ISSUE TITLE
Create a merge tool for the .hypothesis directory

### ISSUE THREAD

**Issue by ckaran** [DRMacIver/hypothesis#82]
I've been using hypothesis for a while now, and have become so dependent on it that I use it on every machine I've got access to.  This is both good and bad; I now have .hypothesis directories on several machines, each of which have different sets of failing examples.  That means that to be sure I've killed a bug, I need to run the same code on multiple different machines, simply because I don't have an easy way of merging the various directories, with their associated examples, into one master directory.  Can you create a tool that can merge multiple .hypothesis directories into one?

Ideally, this would be a tool that is git-compatible.  That is, something where the following works:

> git config --global merge.tool customMergeTool
> git config --global mergetool.customMergeTool.cmd 'customMergeTool.sh \"$BASE\" \"$LOCAL\" \"$REMOTE\" \"$MERGED\"'

See http://stackoverflow.com/questions/23313620/select-git-mergetool-based-on-file-type for more information about this.

The reason I want it to also be git compatible is because I want to commit the .hypothesis directory to my repository; there are cases where something fails, but only VERY rarely.  If we lose that one case, then it will be hard if not impossible to recreate it.  By having the ability to store the directory in the repository, not only do we protect against the loss of a machine with a valuable example, I and my coworkers immediately get access to the failing example, and can independently test our code.  Finally, our build/test farm also gets it, and can do repeated nightly tests, blindly committing the .hypothesis directory, which we can then all pull from the next day to see if there are any new failing examples.

**References:**
http://stackoverflow.com/questions/23313620/select-git-mergetool-based-on-file-type
http://git-scm.com/docs/git-mergetool
http://git-scm.com/docs/git-config search for `mergetool.<tool>.path` and `mergetool.<tool>.cmd`

**Comment by DRMacIver** [comment]
There actually is one! It's not in  release yet but it's stand alone so you can just copy the file. https://github.com/DRMacIver/hypothesis/blob/upcoming/src/hypothesis/tools/mergedbs.py

**Comment by ckaran** [comment]
Man, you're **GOOD!**  OK, this issue should be closed then, I'll wait until the next release and start using it.  Thanks!

**Comment by DRMacIver** [comment]
@charleso As of the 1.7.1 release this is now out there.

BTW, if you're as enthusiastic about Hypothesis as all that, have you considered adding your name to http://hypothesis.readthedocs.org/en/latest/endorsements.html ? :-)

**Comment by ckaran** [comment]
I'd love to, but we're not allowed to endorse stuff where I work at.  :(

Cem

**Comment by DRMacIver** [comment]
Ah, shame. Oh well.

By the way, it occurs to me that you might want to think about using the explicit examples feature: http://hypothesis.readthedocs.org/en/latest/details.html#providing-explicit-examples

You probably shouldn't rely on the database for correctness of your code, because it can and will sometimes drop examples when you e.g. change your tests or upgrade Hypothesis - its behaviour is really intended more like a cache for improving the development workflow than it is to ensure that nothing is ever forgotten.

**Comment by ckaran** [comment]
Yeah, it is a shame.  Sorry...

I'll keep that in mind about the caching behavior, but I think it'll still be useful.  BTW, is there a way of extracting examples from the database automatically?  That way we can store the interesting examples somewhere else, so if an upgrade wipes the database, we still have the examples.

Thanks,
Cem Karan

**Comment by DRMacIver** [comment]
The database never actually gets wiped - all that happens is that some examples may no longer be valid, either because the storage has changed or because you've changed requirements (e.g. if you raise the min_size on a list), and will be ignored.

RE getting the data out: It's possible but kinda fiddly. You' have to reconstruct a bunch of the logic that given uses. The storage API is straightforward enough, but you'd need to construct the relevant eys and strategies yourself (and you do need the strategy - strategies basically act as a schema for the data storage).

**Comment by ckaran** [comment]
Got it.  In that case, I'll leave it alone for now.  As it is, hypothesis is an INCREDIBLY useful tool; everything else I ask for is just icing on the cake.

Thanks,
Cem Karan
